# Generated by Django 4.2.16 on 2024-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="blogs", to="blog.tag"
            ),
        ),
    ]
